#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -u

###### gdu ######
# Fast disk usage analyzer with console interface written in Go (ncdu like).
# https://github.com/dundee/gdu
######
GDU_VERSION=5.13.2

CLI_DIR="${TOOLS_HOME:=/app/local}/bin"
declare -A TARGET_DICT=(
  ["aarch64"]="gdu_linux_arm64"
  ["x86_64"]="gdu_linux_amd64"
)
TARGET="${TARGET_DICT[$(uname --machine)]}"

if ! (type gdu >/dev/null 2>&1); then
  cd "${CLI_DIR}" || exit

  curl -sSL "https://github.com/dundee/gdu/releases/download/v${GDU_VERSION}/${TARGET}.tgz" | tar -xz
  chmod 755 "${TARGET}"
  chown 0:0 "${TARGET}"
  mv "${TARGET}" "gdu"
fi

echo "Gdu $(gdu --version)"
