#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -u

###### fd ######
# A simple, fast and user-friendly alternative to 'find'.
# https://github.com/sharkdp/fd
######
FD_VERSION="8.3.2"

CLI_DIR="${TOOLS_HOME:=/app/local}/bin"
declare -A TARGET_DICT=(
  ["aarch64"]="fd-v${FD_VERSION}-arm-unknown-linux-musleabihf"
  ["x86_64"]="fd-v${FD_VERSION}-x86_64-unknown-linux-musl"
)
TARGET="${TARGET_DICT[$(uname --machine)]}"

if ! (type fd >/dev/null 2>&1); then
  cd "${CLI_DIR}" || exit

  curl -sL \
    "https://github.com/sharkdp/fd/releases/download/v${FD_VERSION}/${TARGET}.tar.gz" |
    tar -xz "${TARGET}/fd" --strip-components 1
  chmod 755 fd
  chown 0:0 fd
fi

fd --version
