#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -u

###### ghq ######
# Remote repository management made easy.
# https://github.com/x-motemen/ghq
######
GHQ_VERSION="1.3.0"

CLI_DIR="${TOOLS_HOME:=/app/local}/bin"
declare -A TARGET_DICT=(
  ["aarch64"]="ghq_linux_arm64"
  ["x86_64"]="ghq_linux_amd64"
)
TARGET="${TARGET_DICT[$(uname --machine)]}"

if ! (type ghq >/dev/null 2>&1); then
  cd "${CLI_DIR}" || exit

  TMPFILE="/tmp/${TARGET}.zip"
  curl -sL \
    "https://github.com/x-motemen/ghq/releases/download/v${GHQ_VERSION}/${TARGET}.zip" \
    -o "${TMPFILE}"
  unzip -j "${TMPFILE}" "${TARGET}/ghq"
  chmod 755 ghq
  chown 0:0 ghq
  rm "${TMPFILE}"
fi

ghq --version
