#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
---
#@ workflow_name = "Docker Release"
name: #@ workflow_name

"on":
  push:
    branches:
      - "main"
    paths: #@ data.values.trigger.paths

jobs:
  update_cache:
    name: docker / update layer cache
    steps:
      -  #@ template.replace(data.values.steps.setup_buildx)
      -  #@ template.replace(data.values.steps.run_buildx)
      -  #@ template.replace(data.values.steps.move_cache)
