name: Docker Release
"on":
  push:
    branches:
    - main
    paths:
    - .dockerignore
    - .dockleignore
    - .github/workflows/docker-*.yml
    - docker/**
jobs:
  update_cache:
    name: docker / update layer cache
    strategy:
      fail-fast: true
      matrix:
        dockerfile: [docker/Dockerfile.build.rust]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ env.CACHE_PREFIX }}-${{ env.CACHE_NAME }}-${{ github.ref }}-${{ hashFiles( matrix.dockerfile ) }}
        restore-keys: |
          ${{ env.CACHE_PREFIX }}-${{ env.CACHE_NAME }}-${{ github.ref }}-
          ${{ env.CACHE_PREFIX }}-${{ env.CACHE_NAME }}-
          ${{ env.CACHE_PREFIX }}-dockerfile-
      env:
        CACHE_PREFIX: ${{ runner.os }}-build
        CACHE_NAME: code-server-dockerfile
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        context: ./docker
        file: ${{ matrix.dockerfile }}
        platforms: |
          linux/amd64
          linux/arm64
        tags: |
          ${{ env.BUILD_IMAGE }}:latest
          ${{ env.BUILD_IMAGE }}:v1
        cache-from: |
          type=local,src=/tmp/.buildx-cache
        cache-to: |
          type=local,dest=/tmp/.buildx-cache-new
      env:
        BUILD_IMAGE: ${{ github.repository }}
    - name: Move Cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    runs-on: ubuntu-20.04
